---
title: "Lecture 9"
author: "Angel Garcia de la Garza"
date: "10/4/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

```

## R Markdown

Dataset to clean the weather dataset

```{r}

library(rnoaa)
library(tidyverse)

weather = 
  meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2016-01-01",
                      date_max = "2016-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, date, month, everything())
weather

```


Group by creates a new dataset with variables grouped. You can do this both ways

```{r}
weather %>%
  group_by(month) %>%
  summarize(n = n())

weather %>%
  count(month)

```

You can use sumamrize and then create new variable based on groups

```{r}
weather %>%
  group_by(month) %>%
  summarize(n_obs = n(),
            n_days = n_distinct(date))
```

Example of plotting

```{r}
weather %>%
  group_by(name, month) %>%
  summarize(mean_tmax = mean(tmax)) %>%
  ggplot(aes(x = month, y = mean_tmax, color = name)) + 
    geom_point() + geom_line() + 
    theme(legend.position = "bottom")
```


This is an example of mutating within group. This will add new variables computed within groups.

```{r}
weather %>%
  group_by(name) %>%
  mutate(centered_tmax = tmax - mean(tmax)) %>% 
  ggplot(aes(x = date, y = centered_tmax, color = name)) + 
    geom_point() 
```

Windows functions take n inputs and return n inputs

```{r}


# To rank
weather %>%
  group_by(name, month) %>%
  mutate(temp_ranking = min_rank(tmax))


# To lag a variable in time
weather %>%
  group_by(name) %>%
  mutate(temp_change = tmax - lag(tmax))

```

