---
title: "Lecture13_DataScrapping"
author: "Angel Garcia de la Garza"
date: "10/23/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading Libraries

```{r}

library(tidyverse)
library(rvest)
library(httr)

```

## Scrapping data


```{r}

url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_xml = read_html(url)

drug_use_xml %>%
  html_nodes(css = "table")

table_marj = (drug_use_xml %>% html_nodes(css = "table"))[[1]] %>%
  html_table()


table_marj = (drug_use_xml %>% html_nodes(css = "table"))[[1]] %>%
  html_table() %>%
  .[-1,] %>% 
  as_tibble()




```

## In class exercise


```{r}
## Test

url <- "https://www.bestplaces.net/cost_of_living/city/new_york/new_york"

cost_living <- read_html(url) %>%
  html_nodes(css = "table") %>%
  .[[2]] %>%
  html_table(header = T) %>%
  as_tibble()

```


## Harry Potter example


```{r}

hpss_html = read_html("http://www.imdb.com/title/tt0241527/")

cast = hpss_html %>%
  html_nodes(".itemprop .itemprop") %>%
  html_text()

```


