---
title: "Lecture 19 Iteration"
author: "Angel Garcia de la Garza"
date: "11/13/2017"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(forcats)
library(stringr)

set.seed(1)

```


## Iteration

```{r create_data}


df <- data_frame(
  
  a = rnorm(20),
  b = rnorm(20),
  c = rnorm(20),
  d = rnorm(20),
  
)

```

```{r zscore}

z_score = function(x) {
  
  z = mean(x) / sd(x)
  z
  
}

z_score(df[[4]])

```


```{r loop_zscore}

output <- vector("list", length = 4)

for (i in 1:4) {
  
  output[[i]] <- z_score(df[[i]])
  
}

output1 = map(df, z_score)
output1 = map_dbl(df, mean)

```


```{r}

z_score = function(x) {
  
  data_frame(
    mean <- mean(x),
    median <- median(x),
    sd <- sd(x)
  )
  
}


output2 = map(df, z_score)

```

#Scrape a lot of URLs

```{r define_url}

url_base = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="
urls = str_c(url_base, 1:10)



```


```{r page_review}

library(rvest)
library(stringr)

read_page_reviews <- function(url) {
  
  h = read_html(url)
  
  title = h %>%
    html_nodes("#cm_cr-review_list .review-title") %>%
    html_text()
  
  stars = h %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("\\d") %>%
    as.numeric()
  
  text = h %>%
    html_nodes(".review-data:nth-child(4)") %>%
    html_text()
  
  data_frame(title, stars, text)
}

dynamite_reviews = map_df(urls, read_page_reviews)

```


```{r lotr_map}


lotr_load_and_tidy = function(path, range, movie_name) {
  
  df = readxl::read_excel(path, range = range) %>%
    janitor::clean_names() %>%
    gather(key = sex, value = words, female:male) %>%
    mutate(race = tolower(race),
           movie = movie_name)
  
  df
  
}


cell_ranges = list("B3:D6", "F3:H6", "J3:L6")
movie_names = list("Fellowship", "Two Towers", "Return")

output = vector("list", 3)

for (i in 1:3) {
  output[[i]] = lotr_load_and_tidy(path = "../lecture18_iteration/data/LotR_Words.xlsx",
                                   range = cell_ranges[[i]],
                                   movie_name = movie_names[[i]])
}


lotr_tidy = bind_rows(output)


## Using this with map2

lotr_tidy = map2_df(.x = cell_ranges, .y = movie_names, 
                    ~lotr_load_and_tidy(path = "../lecture18_iteration/data/LotR_Words.xlsx",
                                        range = .x,
                                        movie_name = .y)) 


lotr_tidy = map2_df(cell_ranges, movie_names, 
                    lotr_load_and_tidy,
                    path = "../lecture18_iteration/data/LotR_Words.xlsx")


```



```{r}

sim_regression = function(n, beta0, beta1) {
  
  sim_data = tibble(
    x = rnorm(n, mean = 1, sd = 1),
    y = beta0 + beta1 * x + rnorm(n, 0, 1)
  )
  
  ls_fit = lm(y ~ x, data = sim_data)
  
  tibble(
    n = n,
    beta0_hat = coef(ls_fit)[1],
    beta1_hat = coef(ls_fit)[2]
  )
}


output = vector("list", 100)

for (i in 1:100) {
  output[[i]] = sim_regression(30, 2, 3)
}

sim_results = bind_rows(output)

## You can also use rerun instead of map to have this run over and over
sim_results = rerun(100, sim_regression(30, 2, 3)) %>% 
  bind_rows()


```

```{r playaround_betas}

sim_results %>% 
  gather(key = parameter, value = estimate, beta0_hat:beta1_hat) %>% 
  group_by(parameter) %>% 
  summarize(emp_mean = mean(estimate),
            emp_var = var(estimate)) %>% 
  knitr::kable(digits = 3)



```

```{r sample_size}


n_samp = list(30, 60, 120, 240)
output = vector("list", length = 4)

for (i in 1:4) {
  output[[i]] = rerun(100, sim_regression(n_samp[[i]], 2, 3)) %>% 
    bind_rows
}



```


```{r}

simulate_n = function(n_rep, n_samp, beta0, beta1) {
  
  rerun(n_rep, sim_regression(n_samp, beta0, beta1)) %>% 
    bind_rows()
  
}

sim_results = 
  map_df(n_samp, simulate_n,
         n_rep = 1000, beta0 = 2, beta1 = 3) 


```



```{r plots}

relabel_function = function(n) { str_c("n = ", n) }

sim_results %>% 
  mutate(n = as.factor(n),
         n = fct_relabel(n, relabel_function)) %>% 
  ggplot(aes(x = n, y = beta1_hat, fill = n)) + 
  geom_violin()


```


