---
title: "Lecture 20 Bootstrap"
author: "Angel Garcia de la Garza"
date: "11/15/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(rnoaa)
library(tidyverse)

theme_set(theme_bw())
theme_update(legend.position = "bottom")

set.seed(1)

```


```{r, cache=TRUE}


library(rnoaa)

weather = 
  meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2016-01-01",
                      date_max = "2016-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

```



```{r}

weather_nest = 
  nest(weather, date:tmin)

weather_nest %>% pull(name)

unnest(weather_nest)

## These two lines do the same thing
weather_nest %>% pull(data)
weather_nest$data

```

```{r}

weather_nest$data[[1]]

lm(tmax ~ tmin, data = weather_nest$data[[1]])


```


```{r}

weather_lm = function(df) {
  lm(tmax ~ tmin, data = df)
}

map(weather_nest$data, weather_lm)

map(weather_nest$data, ~lm(tmax ~ tmin, data = .x))


```


```{r}


weather_nest = 
  weather_nest %>% 
  mutate(models = map(data, weather_lm))


weather_analysis = 
  weather %>% 
  nest(date:tmin) %>% 
  mutate(models = map(data, weather_lm),
         results = map(models, broom::tidy)) %>% 
  select(-data, -models) %>% 
  unnest()


```


```{r}

instacart = read_csv("../data/instacart_train_data.csv.zip")


instacart_nest = 
  instacart %>% 
  group_by(department) %>% 
  nest() %>% 
  filter(department %in% c("deli", "produce", "snacks", "beverages"))



```



```{r}

## You create a summary table of the statistics of hour of the day


instacart_nest %>% 
  mutate(order_hour_summary = map(data, ~summary(.x[["order_hour_of_day"]])),
         tidy_summary = map(order_hour_summary, broom::tidy)) %>% 
  select(-data, -order_hour_summary) %>% 
  unnest()


```


# Bootstrap

```{r}

set.seed(10)

n_samp = 250

sim_df_const = tibble(
  x = rnorm(n_samp, 1, 1),
  error = rnorm(n_samp, 0, 1),
  y = 2 + 3 * x + error
)

sim_df_nonconst = sim_df_const %>% 
  mutate(
  error = error * .75 * x,
  y = 2 + 3 * x + error
)


bind_rows(
  mutate(sim_df_const, data = "sim_df_const"),
  mutate(sim_df_nonconst, data = "sim_df_nonconst")
) %>% 
  ggplot(aes(x = x, y = y)) + 
  geom_point(alpha = .5) +
  stat_smooth(method = "lm") +
  facet_grid(~data) 


```


```{r bootstrap_samples}

boot_sample = function(df) {
  sample_frac(df, replace = TRUE)
}


boot_sample(sim_df_nonconst)


boot_straps = data_frame(
  strap_number = 1:1000,
  strap_sample = rerun(1000, boot_sample(sim_df_nonconst))
)


boot_straps %>% 
  filter(strap_number %in% 1:2) %>% 
  mutate(strap_sample = map(strap_sample, ~arrange(.x, x))) %>% 
  pull(strap_sample)


bootstrap_results = 
  boot_straps %>% 
  mutate(models = map(strap_sample, ~lm(y ~ x, data = .x)),
         results = map(models, broom::tidy)) %>% 
  select(-strap_sample, -models) %>% 
  unnest() %>% 
  group_by(term) %>% 
  summarize(boot_se = sd(estimate))


```


```{r boot_strapplot}

boot_straps %>% 
  unnest() %>% 
  ggplot(aes(x = x, y = y)) + 
  geom_line(aes(group = strap_number), stat = "smooth", method = "lm", se = FALSE, alpha = .1, color = "blue") +
  geom_point(data = sim_df_nonconst, alpha = .5)


```



