---
title: "Lecture 5"
author: "Angel Garcia de la Garza"
date: "9/20/2017"
output: html_document
---
The shortcut to inset r chunks is Command+option+I

```{r library}
#Remove environment variables
rm(list = ls())

#Load tidyverse
library(tidyverse)
```

I will first load the data in R

```{r}

litters_data <- readr::read_csv(file = "./data_import_examples/FAS_litters.csv")

```

In this step I will clean up the names of the dataframe

```{r}

##Print out names of the dataset
names(litters_data)

#Use clean_names from janitor to change the names to snake case
## This is cool
litters_data <- janitor::clean_names(litters_data)
names(litters_data)

##This is an example of reading in a dataset while you specify the class of each column
litters_data <- read_csv(file = "./data_import_examples/FAS_litters.csv",
  col_types = "ccddiiii"
)

## character = c, double = d, integer = i
```

```{r}
##This is a test example

pup_data <- read_csv(file = "./data_import_examples/FAS_pups.csv", 
                     col_types = "ciiiii")

pup_data <- janitor::clean_names(pup_data)

```

Test read excel

```{r}
library("readxl")

mlb11_data <- read_excel("./data_import_examples/mlb11.xlsx", n_max = 20)

```

